name: fight_app2
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+2

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  image_picker: 
  table_calendar: ^3.1.1
  intl: ^0.19.0
  google_fonts: ^6.2.1
  flutter_launcher_icons:
  sqflite: ^2.0.0+4
  flutter_riverpod:
  flutter_hooks:
  freezed_annotation:
  url_launcher: ^6.3.1
  webview_flutter:
  permission_handler:
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  custom_lint: ^0.7.0
  build_runner:
  freezed:

flutter_icons:       
  ios: true
  android: true
  image_path: "assets/images/app_icon.JPG"

flutter:
  uses-material-design: true

  fonts:
    - family: PoetsenOne
      fonts:
        - asset: fonts/Poetsen_One/PoetsenOne-Regular.ttf